banned_words: Hilter, Hitler, Good Stuff, Watch it, adorree, Tik, Tok, TikTok, CORONAVIRUS,
  Corona, black lives matter, BLM, simp, NEGRO, Ahexgao
browser: false
captcha_wait: ''
change_genre: '0'
cookie: !!binary |
  DSADAUZ0FBQUFBJJJJJkRHQzdkeDNCM20xSlpFMS02dkdCdEpqYlVLdmtub0J3TjNwalgxVGVWU1l0UTRk
  d1dKNDRGVUw3R2RqTXRPNXNXQ0E4TEJUSFgyY2JYRllLTlFINDI1amxfMmRV
  cGVk
custom_template: true
default_price: '5'
description: 's'
disable_comments: true
extracookie: ''
filter_percent: '0.7'
genre: '1'
ids: 4776866, 3366519, 3750657, 2924047, 3839201
keywords: ''
max_uploads: ''
min_favs: ''
min_sales: ''
no_dups: false
only_emjoji: false
only_upload: false
pant: true
prefix: ''
price_limit: ''
price_times: ''
set_name: ''
shirt: true
solve_wait: ''
sort_rela: '1'
sort_time: '3'
start_page: '1'
suffix: ''
switch_price: ''
threads: '2'
tshirt: false
upload_wait: ''
usechrome: false
username: DSASDSA
